spring:
  datasource:
    druid:
      test:
        username: root
        password:
        url: jdbc:mysql://127.0.0.1:3307/test
      weixin:
        username: root
        password:
        url: jdbc:mysql://127.0.0.1:3307/my_weixin
      type: com.alibaba.druid.pool.DruidDataSource
      #   数据源其他配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query-timeout: 10000


#debug: true
mybatis:
  mapper-locations: classpath:com/lhzh/jdbcstudy/dao/*Mapper.xml
